package Study;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class FirstServlet extends HttpServlet 
{
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
	{
		// setting http response header  
		response.setContentType("text/html");
		
		PrintWriter pw=response.getWriter();
		
		pw.println("<html>");
		pw.println("<body>");
		pw.println("<h1> This is Generated by Servlet API <h1/>");
		pw.println("</body>");
		pw.println("</html>");
		
	}

}
